export const TYPES = {
  GET_USER: "GET_USER",
  GET_CONTENT: "GET_CONTENT",
  GET_USER_CONTENTS: "GET_USER_CONTENTS",
  GET_CONTENTS: "GET_CONTENTS",
  GET_ALL_CONTENTS: "GET_ALL_CONTENTS",
  SET_USER: "SET_USER",
  CREATE_USER: "CREATE_USER",
  SET_CONTENTS: "SET_CONTENTS",
  SET_CONTENT: "SET_CONTENT",
};
